version: '3.9'

services:
  postgres:
    image: postgres
    container_name: ${POSTGRESQL_DATABASE}
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    ports:
      - "${POSTGRESQL_PORT}:5432"
    volumes:
      - C:\Projetos\Volumes\expense-control:/var/lib/postgresql/data